name: Plugin
version: ${project.version}
main: com.ynov.projet.Main
api-version: 1.15
commands:
  lost:
    description: Permet à un joueur de perdre du chakra.
  build:
    description: permet de mettre un joueur en build, provisoirement ou définitivement